# Generated by Django 2.2.3 on 2019-07-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
