# Generated by Django 2.2.3 on 2019-07-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_idea_ideawriter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='ideawriter',
        ),
    ]
