# Generated by Django 2.2.3 on 2019-07-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190716_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tel',
            new_name='phonenumber',
        ),
    ]
