# Generated by Django 2.2.3 on 2019-07-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20190716_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='votes',
            field=models.IntegerField(default=3),
        ),
    ]
