# Generated by Django 2.2.3 on 2019-07-18 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='votes',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
