# Generated by Django 2.2.3 on 2019-07-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20190718_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='votes',
            field=models.IntegerField(default=2),
        ),
    ]
