# Generated by Django 2.2.3 on 2019-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190718_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urlcontent',
            field=models.URLField(default='www.naver.com'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
